trigger:
- main

variables:
- name: major
  value: 1
- name: minor
  value: 2
- name: patch
  value: 0

name: $(major).$(minor).$(patch)-$(Rev:r)

stages:
- stage: Deploy
  displayName: Deploy
  condition:
    not(eq(variables['build.reason'], 'PullRequest'))
  jobs:
  - job: deploy
    displayName: Deploy Docker Image
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Bash@3
      displayName: Configure Version
      inputs:
        targetType: inline
        script: |
          echo '{ "label" : "'$LABEL'" }' > start-client/BuildVersion.json
      env:
        LABEL: $(Build.BuildNumber)
    - task: Docker@2
      displayName: Build and Push Docker Image
      inputs:
        command: buildAndPush
        containerRegistry: SteeltoeContainerRegistry
        repository: initializr-web
        tags: |
          $(Build.BuildId)
          latest
    - task: ShellScript@2
      displayName: Generate Staging Manifest
      inputs:
        scriptPath: ./yttw.sh
        args: >
          -f kubernetes
          -v image_tag=$(Build.BuildId)
          -v hostname=start-staging.steeltoe.io
          --output-files manifests/staging
    - task: ShellScript@2
      displayName: Generate Production Manifest
      inputs:
        scriptPath: ./yttw.sh
        args: >
          -f kubernetes
          -v image_tag=$(Build.BuildId)
          -v replica_count=2
          -v hostname=start.steeltoe.io
          --output-files manifests/production
    - task: PublishPipelineArtifact@1
      displayName: Publish Manifests
      inputs:
        targetPath: manifests
        artifactName: manifests
