trigger:
  - staging

variables:
  - name: major
    value: 0
  - name: minor
    value: 1
  - name: micro
    value: 0

name: $(major).$(minor).$(micro)-$(Rev:r)

jobs:
  - job: Build
    pool:
      vmImage: ubuntu-latest
    steps:
      - task: Docker@2
        displayName: Push Docker Image
        inputs:
          command: buildAndPush
          containerRegistry: SteeltoeContainerRegistry
          repository: initializr-web
          Dockerfile: start-client/Dockerfile
          buildContext: start-client/
          tags: |
            $(Build.BuildId)
            latest
        condition:
          and(succeeded(), not(eq(variables['build.reason'], 'PullRequest')))
      - task: KubernetesManifest@0
        displayName: Deploy to Staging
        inputs:
          action: deploy
          kubernetesServiceConnection: SteeltoeStagingAKS
          namespace: initializr
          manifests: |
            start-client/deploy/kubernetes/deployment.yaml
            start-client/deploy/kubernetes/service.yaml
          containers: |
            steeltoe.azurecr.io/initializr-web:$(Build.BuildId)
        condition:
          and(succeeded(), not(eq(variables['build.reason'], 'PullRequest')))
