trigger:
  - dev

variables:
  - name: major
    value: 0
  - name: minor
    value: 1
  - name: micro
    value: 0

name: $(major).$(minor).$(micro)-$(Rev:r)

jobs:
  - job: Build
    pool:
      vmImage: ubuntu-latest
    steps:
      - task: Bash@3
        displayName: Configure Version Label
        inputs:
          targetType: inline
          script: |
            echo '{ "label" : "'$LABEL'" }' > start-client/BuildVersion.json
        env:
          LABEL: $(Build.BuildNumber)
      - task: Docker@2
        displayName: Build Docker Image
        inputs:
          command: build
