trigger:
  - dev

variables:
  - name: major
    value: 0
  - name: minor
    value: 1
  - name: micro
    value: 0
  - name: DotNet3Version
    value: 3.1.x
  - name: DOTNET_SKIP_FIRST_TIME_EXPERIENCE
    value: true
  - name: DOTNET_CLI_TELEMETRY_OPTOUT
    value: 1

name: $(major).$(minor).$(micro)-$(Rev:r)

jobs:
  - job: Build
    pool:
      vmImage: windows-latest
    steps:
      - task: UseDotNet@2
        displayName: Prep Dotnet 3
        inputs:
          packageType: sdk
          version: $(DotNet3Version)
      - task: DotNetCoreCLI@2
        displayName: Dotnet Build
        inputs:
          command: build
          arguments: /p:TreatWarningsAsErrors=True
      - task: DotNetCoreCLI@2
        displayName: Dotnet Test
        inputs:
          command: test
          arguments: --no-build /p:CollectCoverage=true /p:CoverletOutputFormat="opencover"
      - task: DotNetCoreCLI@2
        displayName: Dotnet Publish
        inputs:
          command: publish
          arguments: --no-build
          zipAfterPublish: false
      - task: CloudFoundry@1
        displayName: Deploy
        inputs:
          cfEndpoint: PCFone
          org: group-steeltoe
          space: initializr-dev
          deploymentOptions: manifest
          cfManifest: deploy/cloud-foundry/manifest.yaml
        condition:
          and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/dev'), not(eq(variables['build.reason'], 'PullRequest')))
