trigger:
  - spring-starter-port

variables:
  - name: major
    value: 0
  - name: minor
    value: 1
  - name: micro
    value: 0

name: $(major).$(minor).$(micro)-$(Rev:r)

jobs:
  - job: Build
    pool:
      vmImage: ubuntu-latest
    steps:
      - task: CloudFoundryCLIInstall@0
        displayName: Install Cloud Foundry CLI
        inputs:
          cfVersion: 6.51.0
      - task: CloudFoundry@1
        displayName: Deploy
        inputs:
          cfEndpoint: PCFone
          org: group-steeltoe
          space: initializr
          deploymentOptions: manifest
          cfManifest: start-client/deploy/cloud-foundry/manifest.yaml
