trigger:
  - master

variables:
  - name: major
    value: 0
  - name: minor
    value: 1
  - name: micro
    value: 0
  - name: DotNet3Version
    value: 3.1.x
  - name: DOTNET_SKIP_FIRST_TIME_EXPERIENCE
    value: true
  - name: DOTNET_CLI_TELEMETRY_OPTOUT
    value: 1

name: $(major).$(minor).$(micro)-$(Rev:r)

jobs:
  - job: BuildArtifacts
    pool:
      vmImage: Windows-2019
    steps:
      - task: UseDotNet@2
        displayName: Dotnet Prep
        inputs:
          packageType: sdk
          version: $(DotNet3Version)
      - task: DotNetCoreCLI@2
        displayName: Dotnet Restore
        inputs:
          command: restore
      - task: DotNetCoreCLI@2
        displayName: Dotnet Build
        inputs:
          command: build
          arguments: --no-restore /p:TreatWarningsAsErrors=True
      - task: DotNetCoreCLI@2
        displayName: Dotnet Test
        inputs:
          command: test
          arguments: --no-build /p:CollectCoverage=true /p:CoverletOutputFormat="opencover"
