trigger:
  - dev

variables:
  - name: major
    value: 0
  - name: minor
    value: 1
  - name: micro
    value: 0

name: $(major).$(minor).$(micro)-$(Rev:r)

jobs:
  - job: Build
    pool:
      vmImage: ubuntu-latest
    steps:
      - task: Bash@3
        displayName: Noop
        inputs:
          script: echo "someday push to development environment"
