trigger:
  - staging

variables:
  - name: major
    value: 0
  - name: minor
    value: 1
  - name: micro
    value: 0

name: $(major).$(minor).$(micro)-$(Rev:r)

jobs:
  - job: Build
    pool:
      vmImage: ubuntu-latest
    steps:
      - task: Docker@2
        displayName: Push Docker Image
        inputs:
          command: buildAndPush
          containerRegistry: SteeltoeContainerRegistry
          repository: initializr-web
          tags: |
            latest
            $(Build.BuildId)
