---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: initializr-web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: initializr-web
  template:
    metadata:
      labels:
        app: initializr-web
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: initializr-web
        image: steeltoe.azurecr.io/initializr-web
        env:
        - name: GOOGLE_TAGMANAGER_ID
          value: GTM-MPTZGWL
        ports:
        - containerPort: 80
