---
applications:
- name: initializr-start
  buildpacks:
    - https://github.com/cloudfoundry/nodejs-buildpack#v1.7.30
  path: ../..
  command: yarn public-start
  memory: 1024M
  env:
    NPM_CONFIG_PRODUCTION: false
